FROM mcr.microsoft.com/playwright/python:v1.44.0-noble
WORKDIR /app
COPY orchestration/itviec-requirements.txt .
RUN pip install --no-cache-dir -r itviec-requirements.txt
RUN playwright install chromium --with-deps
ENV PYTHONPATH=/app
COPY src/ ./src/
COPY orchestration/ ./orchestration/
COPY dbt_transform/ ./dbt_transform/
RUN cd dbt_transform && dbt deps --profiles-dir .
