FROM prefecthq/prefect:2.16.5-python3.10
WORKDIR /app
COPY orchestration/worker-requirements.txt .
RUN pip install --no-cache-dir -r worker-requirements.txt
ENV PYTHONPATH=/app
COPY src/ ./src/
COPY orchestration/ ./orchestration/
COPY dbt_transform/ ./dbt_transform/
